// Generated by CoffeeScript 1.11.1
(function() {
  var ChatByPhone,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ChatByPhone = (function(superClass) {
    extend(ChatByPhone, superClass);

    function ChatByPhone(user, phone1, config) {
      this.phone = phone1;
      ChatByPhone.__super__.constructor.call(this, user, config);
    }

    ChatByPhone.prototype.start = function(onStart) {
      return this.login((function() {
        return this.getUserInfo(this.phone, (function(toUser) {
          return this.startChatWithUser(toUser, function() {
            return onStart(toUser);
          });
        }).bind(this));
      }).bind(this));
    };

    ChatByPhone.prototype.loginByPhone = function(phone) {
      return this.login(function() {});
    };

    return ChatByPhone;

  })(ChatApi);

  window.ChatByPhone = ChatByPhone;

}).call(this);

//# sourceMappingURL=ChatByPhone.js.map
