// Generated by CoffeeScript 1.12.0
(function() {
  var ChatBox;

  ChatBox = (function() {
    function ChatBox(user, toUserId, chatId) {
      this.userInfo = user;
      this.container = new Element('div.chatBox');
      this.chatMessagesBox = new ChatMessagesBox(this);
      this.answerBox = new Element('div.answerBox').inject(this.container);
      new Element('div.authUser', {
        html: user.login
      }).inject(this.answerBox);
      this.messageInputBox = new MessageInputBox(this);
      this.sendMessageButton = new SendMessageButton(this);
      this.chat = new Chat(user, toUserId, {
        baseUrl: 'http://185.98.87.28:8081'
      });
      if (chatId) {
        console.log('>>> ' + chatId);
        this.chat.start(chatId);
      } else {
        this.chat.start();
      }
      this.chat.bind('joined', (function() {}).bind(this));
      this.chat.bind('newMessage', (function(data) {
        return this.chatMessagesBox.addMessage(this.chat.data.users[data.message.userId], data.message.message, data.message.createTime);
      }).bind(this));
      this.chat.bind('historyLoaded', (function(messages) {
        var i, j, message, ref;
        for (i = j = ref = messages.length - 1; j >= 0; i = j += -1) {
          message = messages[i];
          this.chatMessagesBox.addMessage(this.chat.data.users[message.userId] || ('USER' + message.userId), message.message, message.createTime);
        }
        return this.chatMessagesBox.scrollBottom();
      }).bind(this));
    }

    ChatBox.prototype.loadHistory = function() {};

    ChatBox.prototype.sendMessage = function() {
      var message;
      message = this.messageInputBox.input.get('value');
      if (!message) {
        return;
      }
      this.messageInputBox.disable();
      this.sendMessageButton.disable();
      return this.chat.sendMessage(message, (function() {
        this.messageInputBox.cleanup();
        this.messageInputBox.enable();
        return this.sendMessageButton.enable();
      }).bind(this));
    };

    return ChatBox;

  })();

  window.ChatBox = ChatBox;

}).call(this);

//# sourceMappingURL=ChatBox.js.map
