// Generated by CoffeeScript 1.11.1
(function() {
  var ChatApiStandby,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ChatApiStandby = (function(superClass) {
    extend(ChatApiStandby, superClass);

    function ChatApiStandby() {
      return ChatApiStandby.__super__.constructor.apply(this, arguments);
    }

    ChatApiStandby.prototype.start = function(onStart) {
      return this.login((function() {
        return this.startSocket(this.user.token, onStart);
      }).bind(this));
    };

    ChatApiStandby.prototype.startSocket = function(token, onAuthenticated) {
      var socket;
      socket = ChatApiStandby.__super__.startSocket.call(this, token);
      return socket.on('authenticated', function() {
        return onAuthenticated();
      });
    };

    return ChatApiStandby;

  })(ChatApi);

  window.ChatApiStandby = ChatApiStandby;

}).call(this);

//# sourceMappingURL=ChatApiStandby.js.map
