// Generated by CoffeeScript 1.12.0
(function() {
  var ChatApiBasic;

  ChatApiBasic = (function() {
    function ChatApiBasic(config) {
      this.config = config;
    }

    ChatApiBasic.prototype.request = function(path, request, onComplete) {
      return new Request({
        url: this.config.baseUrl + '/api/v1/' + path,
        onComplete: (function(data) {
          data = JSON.parse(data);
          if (data.error) {
            throw new Error(data.error);
          }
          return onComplete(data);
        }).bind(this)
      }).get(request);
    };

    ChatApiBasic.prototype.startSocket = function(token) {
      var socket;
      this.token = token;
      if (this.config.baseUrl) {
        socket = io.connect(this.config.baseUrl);
      } else {
        socket = io.connect();
      }
      this.socket = socket;
      return socket.on('connect', (function() {
        return socket.emit('authenticate', {
          token: token
        });
      }).bind(this)).on('event', (function(data) {
        console.log(data);
        return this.trigger(data.type, data);
      }).bind(this)).on('unauthorized', function(msg) {
        msg.data.token = token;
        return console.error(msg.data);
      });
    };

    return ChatApiBasic;

  })();

  window.ChatApiBasic = ChatApiBasic;

}).call(this);

//# sourceMappingURL=ChatApiBasic.js.map
