// Generated by CoffeeScript 1.12.0
(function() {
  var ChatMessagesBox;

  ChatMessagesBox = (function() {
    function ChatMessagesBox(chatBox) {
      this.chatBox = chatBox;
      this.container = new Element('div.messagesBox').inject(this.chatBox.container);
    }

    ChatMessagesBox.prototype.addMessage = function(userInfo, text, timestamp) {
      this._addMessage(userInfo, text, timestamp);
      return this.scrollBottom();
    };

    ChatMessagesBox.prototype._addMessage = function(userInfo, text, timestamp) {
      return new MessageBox(this, userInfo, text, timestamp);
    };

    ChatMessagesBox.prototype.scrollBottom = function() {
      return new Fx.Scroll(this.container).toBottom();
    };

    return ChatMessagesBox;

  })();

  window.ChatMessagesBox = ChatMessagesBox;

}).call(this);

//# sourceMappingURL=ChatMessagesBox.js.map
