// Generated by CoffeeScript 1.11.1
(function() {
  var ChatApi;

  ChatApi = (function() {
    function ChatApi(user, config) {
      this.user = user;
      this.config = config;
      if (!this.user) {
        throw new Error('user does not defined');
      }
      MicroEvent.mixin(this);
      this.initDeliveredLogic();
    }

    ChatApi.prototype.restart = function() {
      this.socket.disconnect();
      return this.socket.connect();
    };

    ChatApi.prototype.getUserInfo = function(phone, onComplete) {
      return new Request({
        url: this.config.baseUrl + '/api/v1/user/info',
        onComplete: (function(userInfo) {
          userInfo = JSON.parse(userInfo);
          return onComplete(userInfo);
        })
      }).get({
        phone: phone
      });
    };

    ChatApi.prototype.login = function(onComplete) {
      return new Request({
        url: this.config.baseUrl + '/api/v1/login',
        onComplete: (function(data) {
          data = JSON.parse(data);
          if (data.error) {
            throw new Error(data.error);
          }
          this.user = Object.assign(this.user, data);
          return onComplete();
        }).bind(this)
      }).get(this.user);
    };

    ChatApi.prototype.start = function() {
      throw new Error('abstract');
    };

    ChatApi.prototype.startSocket = function(token) {
      var socket;
      this.token = token;
      if (this.config.baseUrl) {
        socket = io.connect(this.config.baseUrl);
      } else {
        socket = io.connect();
      }
      this.socket = socket;
      return socket.on('connect', (function() {
        return socket.emit('authenticate', {
          token: token
        });
      }).bind(this)).on('event', (function(data) {
        console.log(data);
        return this.trigger(data.type, data);
      }).bind(this)).on('unauthorized', function(msg) {
        return console.log('unauthorized: ' + JSON.stringify(msg.data));
      });
    };

    ChatApi.prototype.initDeliveredLogic = function(chatId) {
      return this.bind('newUserMessages', (function(data) {
        return this.markAsDelivered(data.messages);
      }).bind(this));
    };

    ChatApi.prototype.loadHistory = function() {
      return new Request({
        url: this.config.baseUrl + '/api/v1/message/list',
        onComplete: (function(messages) {
          messages = JSON.parse(messages);
          if (messages.length === 0) {
            return;
          }
          this.markAsDelivered(messages);
          return this.trigger('historyLoaded', messages);
        }).bind(this)
      }).get({
        token: this.token,
        chatId: this.chatId
      });
    };

    ChatApi.prototype.sendMessage = function(message, onComplete) {
      if (!this.chatId) {
        throw new Error('Chat has not started');
      }
      return new Request({
        url: this.config.baseUrl + '/api/v1/message/send',
        onComplete: onComplete
      }).get({
        token: this.token,
        chatId: this.chatId,
        message: message
      });
    };

    ChatApi.prototype.sendUserMessage = function(message, userId, onComplete) {
      if (!this.chatId) {
        throw new Error('Chat has not started');
      }
      return new Request({
        url: this.config.baseUrl + '/api/v1/message/userSend',
        onComplete: onComplete
      }).get({
        token: this.token,
        userId: userId,
        chatId: this.chatId,
        message: message
      });
    };

    ChatApi.prototype.loadUserInfo = function(userId, onComplete) {
      if (userId === 'undefined') {
        throw new Error('!');
      }
      return new Request({
        url: this.config.baseUrl + '/api/v1/user/info',
        onComplete: function(data) {
          data = JSON.parse(data);
          return onComplete(data);
        }
      }).get({
        id: userId
      });
    };

    ChatApi.prototype.markAsDelivered = function(messages) {
      return this.markAs('delivered', messages);
    };

    ChatApi.prototype.markAsViewed = function(messages) {
      return this.markAs('viewed', messages);
    };

    ChatApi.prototype.ucFirst = function(str) {
      var f;
      f = str.charAt(0).toUpperCase();
      return f + str.substr(1, str.length - 1);
    };

    ChatApi.prototype.markAs = function(keyword, messages) {
      var arrangedMessages, chatId, eventType, i, len, message, messageIds, results;
      messages = messages.filter(function(message) {
        return !message[keyword];
      });
      if (messages.length === 0) {
        return;
      }
      arrangedMessages = {};
      for (i = 0, len = messages.length; i < len; i++) {
        message = messages[i];
        if (!message.chatId) {
          throw new Error('message.chatId is required');
        }
        if (!arrangedMessages[message.chatId]) {
          arrangedMessages[message.chatId] = [];
        }
        arrangedMessages[message.chatId].push(message);
      }
      eventType = 'markAs' + this.ucFirst(keyword);
      console.log(eventType);
      results = [];
      for (chatId in arrangedMessages) {
        messages = arrangedMessages[chatId];
        messageIds = messages.map(function(message) {
          return message._id;
        });
        results.push(this.socket.emit(eventType, {
          messageIds: messageIds.join(','),
          chatId: chatId
        }));
      }
      return results;
    };

    return ChatApi;

  })();

  ChatApi.tts = function(timestamp) {
    var date, formattedTime, hours, minutes, monthNames;
    date = new Date(timestamp);
    hours = date.getHours();
    monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    minutes = "0" + date.getMinutes();
    formattedTime = date.getDate() + ' ' + monthNames[date.getMonth()] + ' ' + hours + ':' + minutes.substr(-2);
    return formattedTime;
  };

  window.ChatApi = ChatApi;

}).call(this);

//# sourceMappingURL=ChatApi.js.map
