// Generated by CoffeeScript 1.11.1
(function() {
  var ChatMessagesBox;

  ChatMessagesBox = (function() {
    function ChatMessagesBox(chatBox) {
      this.chatBox = chatBox;
      this.container = new Element('div.messagesBox').inject(this.chatBox.container);
      this.messageBoxes = {};
    }

    ChatMessagesBox.prototype.addMessage = function(userInfo, message) {
      this._addMessage(userInfo, message);
      return this.scrollBottom();
    };

    ChatMessagesBox.prototype._addMessage = function(userInfo, message) {
      var mine;
      mine = this.chatBox.userInfo._id === userInfo._id;
      return this.messageBoxes[message._id] = new MessageBox(this, mine, userInfo, message);
    };

    ChatMessagesBox.prototype.scrollBottom = function() {
      return this.container.scrollTop = this.container.scrollHeight;
    };

    return ChatMessagesBox;

  })();

  window.ChatMessagesBox = ChatMessagesBox;

}).call(this);

//# sourceMappingURL=ChatMessagesBox.js.map
