// Generated by CoffeeScript 1.11.1
(function() {
  var MessageBox;

  MessageBox = (function() {
    function MessageBox(chatMessageBox, mine, userInfo, text, timestamp) {
      var eMark, eText;
      this.chatMessageBox = chatMessageBox;
      this.text = text;
      this.container = new Element('div.messageBox').inject(this.chatMessageBox.container, 'bottom');
      if (mine) {
        this.container.addClass('mine');
      }
      new Element('div.time', {
        html: ChatApi.tts(timestamp)
      }).inject(this.container);
      eMark = new Element('div.mark', {
        html: '&#10004;'
      }).inject(this.container);
      eText = new Element('div.text', {
        html: this.text
      }).inject(this.container);
      if (mine) {
        new Element('div.arrow.right').inject(eText);
      } else {
        new Element('div.arrow.left').inject(eText);
      }
    }

    return MessageBox;

  })();

  window.MessageBox = MessageBox;

}).call(this);

//# sourceMappingURL=MessageBox.js.map
