// Generated by CoffeeScript 1.12.0
(function() {
  var MessageBox;

  MessageBox = (function() {
    function MessageBox(chatMessageBox, userInfo, text, timestamp) {
      this.chatMessageBox = chatMessageBox;
      this.text = text;
      console.log(userInfo);
      this.container = new Element('div.messageBox').inject(this.chatMessageBox.container, 'bottom');
      new Element('div.time', {
        html: Chat.tts(timestamp)
      }).inject(this.container);
      new Element('div.user', {
        html: userInfo.login
      }).inject(this.container);
      new Element('div.text', {
        html: this.text
      }).inject(this.container);
    }

    return MessageBox;

  })();

  window.MessageBox = MessageBox;

}).call(this);

//# sourceMappingURL=MessageBox.js.map
