// Generated by CoffeeScript 1.11.1
(function() {
  var MessageBox;

  MessageBox = (function() {
    function MessageBox(chatMessageBox, mine, userInfo, message) {
      var eText;
      this.chatMessageBox = chatMessageBox;
      this.message = message;
      this.container = new Element('div.messageBox').inject(this.chatMessageBox.container, 'bottom');
      new Element('div.time', {
        html: ChatApi.tts(this.message.createTime)
      }).inject(this.container);
      this.mark = new Element('div.mark').inject(this.container);
      eText = new Element('div.text', {
        html: this.message.message
      }).inject(this.container);
      if (mine) {
        this.container.addClass('mine');
        new Element('div.arrow.right').inject(eText);
      } else {
        new Element('div.arrow.left').inject(eText);
      }
      if (this.message.delivered) {
        this.markAsDelivered();
      }
    }

    MessageBox.prototype.markAsDelivered = function() {
      this.mark.set('title', 'Delivered');
      return this.mark.set('html', '&#10004;');
    };

    MessageBox.prototype.markAsViewed = function() {
      this.mark.set('title', 'Viewed');
      return this.mark.set('html', '&#128065;');
    };

    return MessageBox;

  })();

  window.MessageBox = MessageBox;

}).call(this);

//# sourceMappingURL=MessageBox.js.map
