// Generated by CoffeeScript 1.11.1
(function() {
  var UsersListBox;

  UsersListBox = (function() {
    function UsersListBox(user1, isHomePage, parent) {
      this.user = user1;
      this.isHomePage = isHomePage;
      this.container = new Element('div.usersList').inject(parent);
      this.initHomeButton();
      this.newUsers = new Element('div.title', {
        html: 'Contacts'
      }).inject(this.container);
      this.contacts = new Element('div.contacts').inject(this.container);
      this.newUsers = new Element('div.title', {
        html: 'New Users'
      }).inject(this.container);
      this.newUsers = new Element('div.newUsers').inject(this.container);
      this.users = {};
    }

    UsersListBox.prototype.initHomeButton = function() {
      if (!this.isHomePage) {
        this.homePageBtn = new Element('div.title.btn', {
          html: '« Go home'
        }).inject(this.container);
        return this.homePageBtn.addEvent('click', function() {
          window.location.hash = window.location.hash.replace(/#(.*)\/(\d+)/, '#$1');
          return window.location.reload(true);
        });
      }
    };

    UsersListBox.prototype._addNewUser = function(user, messagesCount) {
      if (this.users[user._id]) {
        return false;
      }
      this.users[user._id] = user;
      this.users[user._id].messageCount = messagesCount;
      this.users[user._id].el = new Element('div.user', {
        html: user.login + '<span>' + this.users[user._id].messageCount + '</span>'
      }).inject(this.container);
      if (user.selected) {
        this.users[user._id].el.addClass('selected');
      }
      this.users[user._id].el.addEvent('click', (function() {
        return this.openChat(user.phone);
      }).bind(this));
      return true;
    };

    UsersListBox.prototype.addNewUser = function(user, messagesCount) {
      if (this._addNewUser(user, messagesCount) === true) {
        return;
      }
      this.users[user._id].messageCount += messagesCount;
      return this.users[user._id].el.getElement('span').set('html', this.users[user._id].messageCount);
    };

    UsersListBox.prototype.openChat = function(phone) {
      window.location = './chat.html#' + this.user.login + '/' + phone;
      return window.location.reload(true);
    };

    UsersListBox.prototype.addNotice = function(userId, notice) {};

    return UsersListBox;

  })();

  window.UsersListBox = UsersListBox;

}).call(this);

//# sourceMappingURL=UsersListBox.js.map
