// Generated by CoffeeScript 1.11.1
(function() {
  var UsersListByPhoneConnect,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  UsersListByPhoneConnect = (function(superClass) {
    extend(UsersListByPhoneConnect, superClass);

    function UsersListByPhoneConnect() {
      return UsersListByPhoneConnect.__super__.constructor.apply(this, arguments);
    }

    return UsersListByPhoneConnect;

  })(UsersListConnect);

  window.UsersListByPhoneConnect = UsersListConnect;

}).call(this);

//# sourceMappingURL=UsersListByPhoneConnect.js.map
