// Generated by CoffeeScript 1.12.0
(function() {
  var ChatScreen;

  ChatScreen = (function() {
    function ChatScreen(api) {
      this.api = api;
      this.container = new Element('div');
      new Element('div.header').inject(this.container);
      this.init();
    }

    ChatScreen.prototype.init = function() {};

    return ChatScreen;

  })();

  window.ChatScreen = ChatScreen;

}).call(this);

//# sourceMappingURL=ChatScreen.js.map
