// Generated by CoffeeScript 1.12.0
(function() {
  var ChatContactsScreen,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ChatContactsScreen = (function(superClass) {
    extend(ChatContactsScreen, superClass);

    function ChatContactsScreen() {
      return ChatContactsScreen.__super__.constructor.apply(this, arguments);
    }

    ChatContactsScreen.prototype.init = function() {
      return this.api.request('contacts/get', {}, function(r) {
        return console.log(r);
      });
    };

    return ChatContactsScreen;

  })(ChatScreen);

  window.ChatContactsScreen = ChatContactsScreen;

}).call(this);

//# sourceMappingURL=ChatContactsScreen.js.map
