// Generated by CoffeeScript 1.11.1
(function() {
  var ChatApp;

  ChatApp = (function() {
    function ChatApp(config) {
      var api, listBox, loginBoxConnect, matchChatWithUser, screen, user;
      this.config = config;
      user = Ngn.LocalStorage.json.get('user');
      if (!user) {
        loginBoxConnect = new LoginBoxConnect(new ChatApiBasic(this.config), new LoginBox(document.getElement('body')));
        return;
      }
      screen = new ChatContactsScreen(new ChatApi(user.token, this.config));
      window.screens = new Screens(document.getElement('body'), screen.container);
      return;
      window.screens = new Screens(document.getElement('body'), loginBoxConnect.loginBox.phoneBox);
      matchChatWithUser = window.location.hash.match(/#(\d+)/);
      if (matchChatWithUser) {
        listBox = new UsersListBox(user, false, document.getElement('body'));
        api = new ChatApiByPhone(user, matchChatWithUser[1], this.config);
        new ChatBoxConnect(api, new ChatBox(document.getElement('body'))).start(function() {
          return new UsersListByPhoneConnect(api, listBox).onStart();
        });
      } else {
        new UsersListConnect(new ChatApiStandby(user, this.config), new UsersListBox(user, true, document.getElement('body'))).start();
        new Element('div.homeBox', {
          html: '<h1>Mersal Chat Client 0.0.2</h1><img src="m/img/chat.svg">'
        }).inject(document.getElement('body'));
      }
    }

    return ChatApp;

  })();

  window.ChatApp = ChatApp;

}).call(this);

//# sourceMappingURL=ChatApp.js.map
