// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    if (window.Notification) {
      $("#requestPermission").on("click", function() {
        return Notification.requestPermission();
      });
      $("#checkPermission").on("click", function() {
        if (Notification.permission) {
          return $("#result").text(Notification.permission);
        } else {
          return $("#result").text((new Notification("check")).permission);
        }
      });
      return $("#show").on("click", function() {
        var notification;
        notification = new Notification($("[name=title]").val(), {
          tag: $("[name=tag]").val(),
          body: $("[name=body]").val(),
          iconUrl: $("[name=icon]").val(),
          icon: $("[name=icon]").val()
        });
        return notification.onclick = function() {
          notification.close();
          window.open().close();
          return window.focus();
        };
      });
    }
  });

}).call(this);

//# sourceMappingURL=ChatNotification.js.map
