// Generated by CoffeeScript 1.12.0
(function() {
  var LoginBox;

  LoginBox = (function() {
    function LoginBox(parent) {
      this.parent = parent;
      this.createPhoneBox();
      this.createCodeBox();
    }

    LoginBox.prototype.titleBox = function() {
      var title;
      title = new Element('div.title');
      new Element('div', {
        html: 'Hi there! Welcome to'
      }).inject(title);
      new Element('img', {
        src: '/m/img/chat-w.svg'
      }).inject(title);
      return title;
    };

    LoginBox.prototype.createPhoneBox = function() {
      this.phoneBox = new Element('div.loginBox.phoneBox.form');
      this.titleBox().inject(this.phoneBox);
      new Element('p.label', {
        html: 'Phone:'
      }).inject(this.phoneBox);
      new Element('span.input', {
        html: '+'
      }).inject(this.phoneBox);
      this.phoneInput = new Element('input', {
        value: '79202560776',
        name: 'phone',
        type: 'tel',
        maxlength: 11
      }).inject(this.phoneBox);
      this.sendCodeButton = new Element('button', {
        html: 'Send code to sms'
      }).inject(this.phoneBox);
      return new Element('button.pseudo', {
        html: 'I already have the code'
      }).addEvent('click', (function() {
        return this.switchToCodeBox();
      }).bind(this)).inject(this.phoneBox);
    };

    LoginBox.prototype.createCodeBox = function() {
      this.codeBox = new Element('div.loginBox.codeBox.form');
      this.titleBox().inject(this.codeBox);
      new Element('p.label', {
        html: 'Input code has sent to you by SMS in field below:'
      }).inject(this.codeBox);
      this.codeInput = new Element('input', {
        name: 'code',
        type: 'number',
        maxlength: 4
      }).inject(this.codeBox);
      this.loginButton = new Element('button', {
        html: 'Login'
      }).inject(this.codeBox);
      return new Element('button.pseudo', {
        html: '&#8701; Go back to phone input'
      }).addEvent('click', (function() {
        return this.switchToLoginBox();
      }).bind(this)).inject(this.codeBox);
    };

    LoginBox.prototype.getPhone = function() {
      return this.phoneInput.get('value');
    };

    LoginBox.prototype.getCode = function() {
      return this.codeInput.get('value');
    };

    LoginBox.prototype.switchToCodeBox = function() {
      if (!this.phoneInput.get('value')) {
        alert('Phone is required');
        return;
      }
      return screens.changeScreen(this.codeBox);
    };

    LoginBox.prototype.switchToLoginBox = function() {
      return screens.changeScreen(this.phoneBox, 'left');
    };

    return LoginBox;

  })();

  window.LoginBox = LoginBox;

}).call(this);

//# sourceMappingURL=LoginBox.js.map
