// Generated by CoffeeScript 1.12.0
(function() {
  var UsersListBox;

  UsersListBox = (function() {
    function UsersListBox(user1, isHomePage, parent) {
      this.user = user1;
      this.isHomePage = isHomePage;
      this.container = new Element('div.usersList').inject(parent);
      this.initHomeButton();
      new Element('div.title', {
        html: 'Contacts'
      }).inject(this.container);
      this.contacts = new Element('div.contacts').inject(this.container);
      new Element('div.title', {
        html: 'New Users'
      }).inject(this.container);
      this.newUsers = new Element('div.newUsers').inject(this.container);
      this.initLogoutButton();
      this.users = {};
    }

    UsersListBox.prototype.initLogoutButton = function() {
      var logoutBtn;
      logoutBtn = new Element('div.title.btn', {
        html: 'Logout'
      }).inject(this.container);
      return logoutBtn.addEvent('click', function(e) {
        e.preventDefault();
        Ngn.LocalStorage.remove('user');
        window.location = './';
        return window.location.reload(true);
      });
    };

    UsersListBox.prototype.initHomeButton = function() {
      if (!this.isHomePage) {
        this.homePageBtn = new Element('div.title.btn', {
          html: '« Go home'
        }).inject(this.container);
        return this.homePageBtn.addEvent('click', function() {
          window.location.hash = '';
          return window.location.reload(true);
        });
      }
    };

    UsersListBox.prototype._addUser = function(user, messagesCount, isNew) {
      var container, countTag;
      if (this.users[user._id]) {
        return false;
      }
      if (isNew) {
        container = this.newUsers;
      } else {
        container = this.contacts;
      }
      this.users[user._id] = user;
      this.users[user._id].messageCount = messagesCount;
      if (this.users[user._id].messageCount) {
        countTag = '<span>' + this.users[user._id].messageCount + '</span>';
      } else {
        countTag = '';
      }
      this.users[user._id].el = new Element('div.user', {
        html: (user.login || user.phone) + countTag
      }).inject(container);
      if (user.selected) {
        this.users[user._id].el.addClass('selected');
      }
      this.users[user._id].el.addEvent('click', (function() {
        return this.openChat(user.phone);
      }).bind(this));
      return true;
    };

    UsersListBox.prototype.addUser = function(user, messagesCount) {
      if (this._addUser(user, messagesCount) === true) {
        return;
      }
      this.users[user._id].messageCount += messagesCount;
      return this.users[user._id].el.getElement('span').set('html', this.users[user._id].messageCount);
    };

    UsersListBox.prototype.openChat = function(phone) {
      window.location.hash = '#' + phone;
      return window.location.reload(true);
    };

    UsersListBox.prototype.addNotice = function(userId, notice) {};

    return UsersListBox;

  })();

  window.UsersListBox = UsersListBox;

}).call(this);

//# sourceMappingURL=UsersListBox.js.map
